// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://tflmntmxnuahlzobwwzh.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InRmbG1udG14bnVhaGx6b2J3d3poIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTU3OTA5MTQsImV4cCI6MjA3MTM2NjkxNH0.5PU2j4kOcKaq4W9FDdXlT5I2UkpwpsLIomQ0YeDWgaI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});